server:
  port: 9999 
spring:
  application:
    name: uk-code-service 

sidecar:
  port: 8080
  health-uri: http://0.0.0.0:8080/health
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/