server:
  port: 9999 
spring:
  application:
    name: uk-code-service
      
sidecar:
  hostname: ukcode
  port: 8082
  health-url: http://${sidecar.ukcode}:${sidecar.port}/health
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
