server:
  port: 9999 
spring:
  application:
    name: premise-service 

sidecar:
  port: 8000 
  health-uri: http://localhost:8000/health
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
